// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ad_accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdAccount = `-- name: CreateAdAccount :one
INSERT INTO ad_accounts (workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, status, connected_at, page_id, pixel_id, name
`

type CreateAdAccountParams struct {
	WorkspaceID           pgtype.UUID
	Platform              string
	ExternalAccountID     string
	AccessTokenEncrypted  string
	RefreshTokenEncrypted pgtype.Text
	TokenExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateAdAccount(ctx context.Context, arg CreateAdAccountParams) (AdAccount, error) {
	row := q.db.QueryRow(ctx, createAdAccount,
		arg.WorkspaceID,
		arg.Platform,
		arg.ExternalAccountID,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
	)
	var i AdAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.Status,
		&i.ConnectedAt,
		&i.PageID,
		&i.PixelID,
		&i.Name,
	)
	return i, err
}

const deleteAdAccount = `-- name: DeleteAdAccount :exec
DELETE FROM ad_accounts WHERE id = $1
`

func (q *Queries) DeleteAdAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdAccount, id)
	return err
}

const deleteAdAccountByWorkspaceAndPlatform = `-- name: DeleteAdAccountByWorkspaceAndPlatform :exec
DELETE FROM ad_accounts WHERE workspace_id = $1 AND platform = $2
`

type DeleteAdAccountByWorkspaceAndPlatformParams struct {
	WorkspaceID pgtype.UUID
	Platform    string
}

func (q *Queries) DeleteAdAccountByWorkspaceAndPlatform(ctx context.Context, arg DeleteAdAccountByWorkspaceAndPlatformParams) error {
	_, err := q.db.Exec(ctx, deleteAdAccountByWorkspaceAndPlatform, arg.WorkspaceID, arg.Platform)
	return err
}

const deleteAdAccountForWorkspace = `-- name: DeleteAdAccountForWorkspace :exec
DELETE FROM ad_accounts WHERE id = $1 AND workspace_id = $2
`

type DeleteAdAccountForWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) DeleteAdAccountForWorkspace(ctx context.Context, arg DeleteAdAccountForWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteAdAccountForWorkspace, arg.ID, arg.WorkspaceID)
	return err
}

const getAdAccountByID = `-- name: GetAdAccountByID :one
SELECT id, workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, status, connected_at, page_id, pixel_id, name FROM ad_accounts WHERE id = $1
`

func (q *Queries) GetAdAccountByID(ctx context.Context, id pgtype.UUID) (AdAccount, error) {
	row := q.db.QueryRow(ctx, getAdAccountByID, id)
	var i AdAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.Status,
		&i.ConnectedAt,
		&i.PageID,
		&i.PixelID,
		&i.Name,
	)
	return i, err
}

const getAdAccountForWorkspace = `-- name: GetAdAccountForWorkspace :one
SELECT id, workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, status, connected_at, page_id, pixel_id, name FROM ad_accounts WHERE id = $1 AND workspace_id = $2
`

type GetAdAccountForWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetAdAccountForWorkspace(ctx context.Context, arg GetAdAccountForWorkspaceParams) (AdAccount, error) {
	row := q.db.QueryRow(ctx, getAdAccountForWorkspace, arg.ID, arg.WorkspaceID)
	var i AdAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.Status,
		&i.ConnectedAt,
		&i.PageID,
		&i.PixelID,
		&i.Name,
	)
	return i, err
}

const getAdAccountsByWorkspace = `-- name: GetAdAccountsByWorkspace :many
SELECT id, workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, status, connected_at, page_id, pixel_id, name FROM ad_accounts WHERE workspace_id = $1 ORDER BY connected_at DESC
`

func (q *Queries) GetAdAccountsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]AdAccount, error) {
	rows, err := q.db.Query(ctx, getAdAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdAccount
	for rows.Next() {
		var i AdAccount
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Platform,
			&i.ExternalAccountID,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.TokenExpiresAt,
			&i.Status,
			&i.ConnectedAt,
			&i.PageID,
			&i.PixelID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdAccountPageAndPixel = `-- name: SetAdAccountPageAndPixel :one
UPDATE ad_accounts SET page_id = $2, pixel_id = $3 WHERE id = $1
RETURNING id, workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, status, connected_at, page_id, pixel_id, name
`

type SetAdAccountPageAndPixelParams struct {
	ID      pgtype.UUID
	PageID  pgtype.Text
	PixelID pgtype.Text
}

func (q *Queries) SetAdAccountPageAndPixel(ctx context.Context, arg SetAdAccountPageAndPixelParams) (AdAccount, error) {
	row := q.db.QueryRow(ctx, setAdAccountPageAndPixel, arg.ID, arg.PageID, arg.PixelID)
	var i AdAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.Status,
		&i.ConnectedAt,
		&i.PageID,
		&i.PixelID,
		&i.Name,
	)
	return i, err
}

const upsertAdAccount = `-- name: UpsertAdAccount :one
INSERT INTO ad_accounts (workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, name, status, connected_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active', now())
ON CONFLICT (workspace_id, platform, external_account_id) DO UPDATE
SET access_token_encrypted = EXCLUDED.access_token_encrypted,
    refresh_token_encrypted = EXCLUDED.refresh_token_encrypted,
    token_expires_at = EXCLUDED.token_expires_at,
    name = EXCLUDED.name,
    status = 'active',
    connected_at = now()
RETURNING id, workspace_id, platform, external_account_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, status, connected_at, page_id, pixel_id, name
`

type UpsertAdAccountParams struct {
	WorkspaceID           pgtype.UUID
	Platform              string
	ExternalAccountID     string
	AccessTokenEncrypted  string
	RefreshTokenEncrypted pgtype.Text
	TokenExpiresAt        pgtype.Timestamptz
	Name                  pgtype.Text
}

func (q *Queries) UpsertAdAccount(ctx context.Context, arg UpsertAdAccountParams) (AdAccount, error) {
	row := q.db.QueryRow(ctx, upsertAdAccount,
		arg.WorkspaceID,
		arg.Platform,
		arg.ExternalAccountID,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.Name,
	)
	var i AdAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.Status,
		&i.ConnectedAt,
		&i.PageID,
		&i.PixelID,
		&i.Name,
	)
	return i, err
}
