// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaignAction = `-- name: CreateCampaignAction :one
INSERT INTO campaign_actions (workspace_id, actor, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, actor, type, status, payload, result, error, created_at, updated_at
`

type CreateCampaignActionParams struct {
	WorkspaceID pgtype.UUID
	Actor       string
	Type        string
	Payload     []byte
}

func (q *Queries) CreateCampaignAction(ctx context.Context, arg CreateCampaignActionParams) (CampaignAction, error) {
	row := q.db.QueryRow(ctx, createCampaignAction,
		arg.WorkspaceID,
		arg.Actor,
		arg.Type,
		arg.Payload,
	)
	var i CampaignAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Actor,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignActionByIDForWorkspace = `-- name: GetCampaignActionByIDForWorkspace :one
SELECT id, workspace_id, actor, type, status, payload, result, error, created_at, updated_at FROM campaign_actions WHERE id = $1 AND workspace_id = $2
`

type GetCampaignActionByIDForWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetCampaignActionByIDForWorkspace(ctx context.Context, arg GetCampaignActionByIDForWorkspaceParams) (CampaignAction, error) {
	row := q.db.QueryRow(ctx, getCampaignActionByIDForWorkspace, arg.ID, arg.WorkspaceID)
	var i CampaignAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Actor,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignActionsByWorkspace = `-- name: ListCampaignActionsByWorkspace :many
SELECT id, workspace_id, actor, type, status, payload, result, error, created_at, updated_at FROM campaign_actions WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCampaignActionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]CampaignAction, error) {
	rows, err := q.db.Query(ctx, listCampaignActionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignAction
	for rows.Next() {
		var i CampaignAction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Actor,
			&i.Type,
			&i.Status,
			&i.Payload,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignActionResult = `-- name: UpdateCampaignActionResult :one
UPDATE campaign_actions
SET status = $2, result = $3, error = $4, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, actor, type, status, payload, result, error, created_at, updated_at
`

type UpdateCampaignActionResultParams struct {
	ID     pgtype.UUID
	Status string
	Result []byte
	Error  pgtype.Text
}

func (q *Queries) UpdateCampaignActionResult(ctx context.Context, arg UpdateCampaignActionResultParams) (CampaignAction, error) {
	row := q.db.QueryRow(ctx, updateCampaignActionResult,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Error,
	)
	var i CampaignAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Actor,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
