// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
RETURNING id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale
`

type CreateCampaignParams struct {
	WorkspaceID          pgtype.UUID
	AdAccountID          pgtype.UUID
	ExternalCampaignID   string
	Name                 string
	Objective            pgtype.Text
	Status               string
	DailyBudget          pgtype.Numeric
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	Cta                  pgtype.Text
	Targeting            []byte
	ExternalAdsetID      pgtype.Text
	ExternalAdID         pgtype.Text
	ExternalCreativeID   pgtype.Text
	Creative             []byte
	BidStrategy          pgtype.Text
	BidCap               pgtype.Numeric
	PacingType           pgtype.Text
	FrequencyCap         pgtype.Int4
	FrequencyCapTimeUnit pgtype.Text
	Variants             []byte
	Provenance           []byte
	Rationale            []byte
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.WorkspaceID,
		arg.AdAccountID,
		arg.ExternalCampaignID,
		arg.Name,
		arg.Objective,
		arg.Status,
		arg.DailyBudget,
		arg.StartDate,
		arg.EndDate,
		arg.Cta,
		arg.Targeting,
		arg.ExternalAdsetID,
		arg.ExternalAdID,
		arg.ExternalCreativeID,
		arg.Creative,
		arg.BidStrategy,
		arg.BidCap,
		arg.PacingType,
		arg.FrequencyCap,
		arg.FrequencyCapTimeUnit,
		arg.Variants,
		arg.Provenance,
		arg.Rationale,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}

const getCampaignByIDForWorkspace = `-- name: GetCampaignByIDForWorkspace :one
SELECT id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale FROM campaigns WHERE id = $1 AND workspace_id = $2
`

type GetCampaignByIDForWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetCampaignByIDForWorkspace(ctx context.Context, arg GetCampaignByIDForWorkspaceParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByIDForWorkspace, arg.ID, arg.WorkspaceID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}

const getCampaignsByWorkspace = `-- name: GetCampaignsByWorkspace :many
SELECT id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale FROM campaigns WHERE workspace_id = $1
`

func (q *Queries) GetCampaignsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, getCampaignsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AdAccountID,
			&i.ExternalCampaignID,
			&i.Name,
			&i.Objective,
			&i.Status,
			&i.DailyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.EndDate,
			&i.Cta,
			&i.Targeting,
			&i.ExternalAdsetID,
			&i.ExternalAdID,
			&i.ExternalCreativeID,
			&i.Creative,
			&i.BidStrategy,
			&i.BidCap,
			&i.PacingType,
			&i.FrequencyCap,
			&i.FrequencyCapTimeUnit,
			&i.Variants,
			&i.Provenance,
			&i.Rationale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignRationale = `-- name: UpdateCampaignRationale :one
UPDATE campaigns SET rationale = $2, updated_at = now() WHERE id = $1
RETURNING id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale
`

type UpdateCampaignRationaleParams struct {
	ID        pgtype.UUID
	Rationale []byte
}

func (q *Queries) UpdateCampaignRationale(ctx context.Context, arg UpdateCampaignRationaleParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignRationale, arg.ID, arg.Rationale)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}

const getCampaignsWithLatestSnapshot = `-- name: GetCampaignsWithLatestSnapshot :many
SELECT
    c.id, c.workspace_id, c.ad_account_id, c.external_campaign_id, c.name, c.objective, c.status, c.daily_budget, c.created_at, c.updated_at,
    ps.id AS snapshot_id, ps.date AS snapshot_date, ps.spend, ps.impressions, ps.clicks, ps.conversions, ps.reach, ps.cpm, ps.cpc, ps.ctr, ps.roas, ps.currency
FROM campaigns c
LEFT JOIN LATERAL (
    SELECT id, date, spend, impressions, clicks, conversions, reach, cpm, cpc, ctr, roas, currency
    FROM performance_snapshots
    WHERE campaign_id = c.id
    ORDER BY date DESC
    LIMIT 1
) ps ON true
WHERE c.workspace_id = $1
ORDER BY c.created_at DESC
`

type GetCampaignsWithLatestSnapshotRow struct {
	ID                 pgtype.UUID
	WorkspaceID        pgtype.UUID
	AdAccountID        pgtype.UUID
	ExternalCampaignID string
	Name               string
	Objective          pgtype.Text
	Status             string
	DailyBudget        pgtype.Numeric
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	SnapshotID         pgtype.UUID
	SnapshotDate       pgtype.Date
	Spend              pgtype.Numeric
	Impressions        pgtype.Int8
	Clicks             pgtype.Int8
	Conversions        pgtype.Int8
	Reach              pgtype.Int8
	Cpm                pgtype.Numeric
	Cpc                pgtype.Numeric
	Ctr                pgtype.Numeric
	Roas               pgtype.Numeric
	Currency           pgtype.Text
}

func (q *Queries) GetCampaignsWithLatestSnapshot(ctx context.Context, workspaceID pgtype.UUID) ([]GetCampaignsWithLatestSnapshotRow, error) {
	rows, err := q.db.Query(ctx, getCampaignsWithLatestSnapshot, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignsWithLatestSnapshotRow
	for rows.Next() {
		var i GetCampaignsWithLatestSnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AdAccountID,
			&i.ExternalCampaignID,
			&i.Name,
			&i.Objective,
			&i.Status,
			&i.DailyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnapshotID,
			&i.SnapshotDate,
			&i.Spend,
			&i.Impressions,
			&i.Clicks,
			&i.Conversions,
			&i.Reach,
			&i.Cpm,
			&i.Cpc,
			&i.Ctr,
			&i.Roas,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignDeliverable = `-- name: UpdateCampaignDeliverable :one
UPDATE campaigns
SET external_campaign_id = $2, external_adset_id = $3, external_creative_id = $4, external_ad_id = $5, status = $6, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale
`

type UpdateCampaignDeliverableParams struct {
	ID                 pgtype.UUID
	ExternalCampaignID string
	ExternalAdsetID    pgtype.Text
	ExternalCreativeID pgtype.Text
	ExternalAdID       pgtype.Text
	Status             string
}

func (q *Queries) UpdateCampaignDeliverable(ctx context.Context, arg UpdateCampaignDeliverableParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignDeliverable,
		arg.ID,
		arg.ExternalCampaignID,
		arg.ExternalAdsetID,
		arg.ExternalCreativeID,
		arg.ExternalAdID,
		arg.Status,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}

const upsertCampaign = `-- name: UpsertCampaign :one
INSERT INTO campaigns (workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (ad_account_id, external_campaign_id)
DO UPDATE SET name = EXCLUDED.name, objective = EXCLUDED.objective, status = EXCLUDED.status, daily_budget = EXCLUDED.daily_budget, updated_at = now()
RETURNING id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale
`

type UpsertCampaignParams struct {
	WorkspaceID        pgtype.UUID
	AdAccountID        pgtype.UUID
	ExternalCampaignID string
	Name               string
	Objective          pgtype.Text
	Status             string
	DailyBudget        pgtype.Numeric
}

func (q *Queries) UpsertCampaign(ctx context.Context, arg UpsertCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, upsertCampaign,
		arg.WorkspaceID,
		arg.AdAccountID,
		arg.ExternalCampaignID,
		arg.Name,
		arg.Objective,
		arg.Status,
		arg.DailyBudget,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns SET status = $2, updated_at = now() WHERE id = $1
RETURNING id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}

const updateCampaignDailyBudget = `-- name: UpdateCampaignDailyBudget :one
UPDATE campaigns SET daily_budget = $2, updated_at = now() WHERE id = $1
RETURNING id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale
`

type UpdateCampaignDailyBudgetParams struct {
	ID          pgtype.UUID
	DailyBudget pgtype.Numeric
}

func (q *Queries) UpdateCampaignDailyBudget(ctx context.Context, arg UpdateCampaignDailyBudgetParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignDailyBudget, arg.ID, arg.DailyBudget)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}

const updateCampaignProvenance = `-- name: UpdateCampaignProvenance :one
UPDATE campaigns SET provenance = $2, updated_at = now() WHERE id = $1
RETURNING id, workspace_id, ad_account_id, external_campaign_id, name, objective, status, daily_budget, created_at, updated_at, start_date, end_date, cta, targeting, external_adset_id, external_ad_id, external_creative_id, creative, bid_strategy, bid_cap, pacing_type, frequency_cap, frequency_cap_time_unit, variants, provenance, rationale
`

type UpdateCampaignProvenanceParams struct {
	ID         pgtype.UUID
	Provenance []byte
}

func (q *Queries) UpdateCampaignProvenance(ctx context.Context, arg UpdateCampaignProvenanceParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignProvenance, arg.ID, arg.Provenance)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Cta,
		&i.Targeting,
		&i.ExternalAdsetID,
		&i.ExternalAdID,
		&i.ExternalCreativeID,
		&i.Creative,
		&i.BidStrategy,
		&i.BidCap,
		&i.PacingType,
		&i.FrequencyCap,
		&i.FrequencyCapTimeUnit,
		&i.Variants,
		&i.Provenance,
		&i.Rationale,
	)
	return i, err
}
