// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommissionBySnapshot = `-- name: GetCommissionBySnapshot :one
SELECT id, workspace_id, ad_account_id, snapshot_id, currency, base_minor, rate_bps, commission_minor, fx_rate, created_at FROM commissions WHERE snapshot_id = $1
`

func (q *Queries) GetCommissionBySnapshot(ctx context.Context, snapshotID pgtype.UUID) (Commission, error) {
	row := q.db.QueryRow(ctx, getCommissionBySnapshot, snapshotID)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.SnapshotID,
		&i.Currency,
		&i.BaseMinor,
		&i.RateBps,
		&i.CommissionMinor,
		&i.FxRate,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommission = `-- name: InsertCommission :one
INSERT INTO commissions (workspace_id, ad_account_id, snapshot_id, currency, base_minor, rate_bps, commission_minor, fx_rate)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (snapshot_id) DO UPDATE SET snapshot_id = EXCLUDED.snapshot_id
RETURNING id, workspace_id, ad_account_id, snapshot_id, currency, base_minor, rate_bps, commission_minor, fx_rate, created_at
`

type InsertCommissionParams struct {
	WorkspaceID     pgtype.UUID
	AdAccountID     pgtype.UUID
	SnapshotID      pgtype.UUID
	Currency        string
	BaseMinor       int64
	RateBps         int32
	CommissionMinor int64
	FxRate          pgtype.Numeric
}

func (q *Queries) InsertCommission(ctx context.Context, arg InsertCommissionParams) (Commission, error) {
	row := q.db.QueryRow(ctx, insertCommission,
		arg.WorkspaceID,
		arg.AdAccountID,
		arg.SnapshotID,
		arg.Currency,
		arg.BaseMinor,
		arg.RateBps,
		arg.CommissionMinor,
		arg.FxRate,
	)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdAccountID,
		&i.SnapshotID,
		&i.Currency,
		&i.BaseMinor,
		&i.RateBps,
		&i.CommissionMinor,
		&i.FxRate,
		&i.CreatedAt,
	)
	return i, err
}

const listCommissionsByWorkspace = `-- name: ListCommissionsByWorkspace :many
SELECT id, workspace_id, ad_account_id, snapshot_id, currency, base_minor, rate_bps, commission_minor, fx_rate, created_at FROM commissions
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListCommissionsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Limit       int32
}

func (q *Queries) ListCommissionsByWorkspace(ctx context.Context, arg ListCommissionsByWorkspaceParams) ([]Commission, error) {
	rows, err := q.db.Query(ctx, listCommissionsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commission
	for rows.Next() {
		var i Commission
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AdAccountID,
			&i.SnapshotID,
			&i.Currency,
			&i.BaseMinor,
			&i.RateBps,
			&i.CommissionMinor,
			&i.FxRate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
