// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (workspace_id, mode)
VALUES ($1, $2)
RETURNING id, workspace_id, mode, created_at
`

type CreateConversationParams struct {
	WorkspaceID pgtype.UUID
	Mode        string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.WorkspaceID, arg.Mode)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, workspace_id, mode, created_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}
