// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (workspace_id, kind, storage_key, public_url, mime, bytes, width, height, duration_ms, checksum, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, kind, storage_key, public_url, mime, bytes, width, height, duration_ms, checksum, status, platform_hashes, created_at, updated_at
`

type CreateMediaAssetParams struct {
	WorkspaceID pgtype.UUID
	Kind        string
	StorageKey  string
	PublicUrl   string
	Mime        string
	Bytes       int64
	Width       pgtype.Int4
	Height      pgtype.Int4
	DurationMs  pgtype.Int8
	Checksum    pgtype.Text
	Status      string
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.WorkspaceID,
		arg.Kind,
		arg.StorageKey,
		arg.PublicUrl,
		arg.Mime,
		arg.Bytes,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Checksum,
		arg.Status,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.StorageKey,
		&i.PublicUrl,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Checksum,
		&i.Status,
		&i.PlatformHashes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaAsset = `-- name: DeleteMediaAsset :exec
DELETE FROM media_assets WHERE id = $1 AND workspace_id = $2
`

type DeleteMediaAssetParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) DeleteMediaAsset(ctx context.Context, arg DeleteMediaAssetParams) error {
	_, err := q.db.Exec(ctx, deleteMediaAsset, arg.ID, arg.WorkspaceID)
	return err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, workspace_id, kind, storage_key, public_url, mime, bytes, width, height, duration_ms, checksum, status, platform_hashes, created_at, updated_at FROM media_assets WHERE id = $1 AND workspace_id = $2
`

type GetMediaAssetParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetMediaAsset(ctx context.Context, arg GetMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, arg.ID, arg.WorkspaceID)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.StorageKey,
		&i.PublicUrl,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Checksum,
		&i.Status,
		&i.PlatformHashes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT id, workspace_id, kind, storage_key, public_url, mime, bytes, width, height, duration_ms, checksum, status, platform_hashes, created_at, updated_at FROM media_assets
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMediaAssets(ctx context.Context, workspaceID pgtype.UUID) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssets, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.StorageKey,
			&i.PublicUrl,
			&i.Mime,
			&i.Bytes,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Checksum,
			&i.Status,
			&i.PlatformHashes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMediaAssetPlatformHash = `-- name: SetMediaAssetPlatformHash :one
UPDATE media_assets
SET platform_hashes = $2, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, kind, storage_key, public_url, mime, bytes, width, height, duration_ms, checksum, status, platform_hashes, created_at, updated_at
`

type SetMediaAssetPlatformHashParams struct {
	ID             pgtype.UUID
	PlatformHashes []byte
}

func (q *Queries) SetMediaAssetPlatformHash(ctx context.Context, arg SetMediaAssetPlatformHashParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, setMediaAssetPlatformHash, arg.ID, arg.PlatformHashes)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.StorageKey,
		&i.PublicUrl,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Checksum,
		&i.Status,
		&i.PlatformHashes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
