// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdAccount struct {
	ID                    pgtype.UUID
	WorkspaceID           pgtype.UUID
	Platform              string
	ExternalAccountID     string
	AccessTokenEncrypted  string
	RefreshTokenEncrypted pgtype.Text
	TokenExpiresAt        pgtype.Timestamptz
	Status                string
	ConnectedAt           pgtype.Timestamptz
	PageID                pgtype.Text
	PixelID               pgtype.Text
	Name                  pgtype.Text
	BillingMode           string
	Payer                 string
	PaymentInstrument     pgtype.Text
	Currency              string
	SpendLimitMinor       pgtype.Int8
}

type BillingProfile struct {
	ID                   pgtype.UUID
	WorkspaceID          pgtype.UUID
	ProviderCustomerID   pgtype.Text
	DefaultPaymentMethod pgtype.Text
	BillingMode          string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Campaign struct {
	ID                   pgtype.UUID
	WorkspaceID          pgtype.UUID
	AdAccountID          pgtype.UUID
	ExternalCampaignID   string
	Name                 string
	Objective            pgtype.Text
	Status               string
	DailyBudget          pgtype.Numeric
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	Cta                  pgtype.Text
	Targeting            []byte
	ExternalAdsetID      pgtype.Text
	ExternalAdID         pgtype.Text
	ExternalCreativeID   pgtype.Text
	Creative             []byte
	BidStrategy          string
	BidCap               pgtype.Numeric
	PacingType           string
	FrequencyCap         pgtype.Int4
	FrequencyCapTimeUnit pgtype.Text
	Variants             []byte
	Provenance           []byte
	Rationale            []byte
}

type CampaignAction struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Actor       string
	Type        string
	Status      string
	Payload     []byte
	Result      []byte
	Error       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Commission struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	AdAccountID     pgtype.UUID
	SnapshotID      pgtype.UUID
	Currency        string
	BaseMinor       int64
	RateBps         int32
	CommissionMinor int64
	FxRate          pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
}

type Conversation struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Mode        string
	CreatedAt   pgtype.Timestamptz
}

type MediaAsset struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	Kind           string
	StorageKey     string
	PublicUrl      string
	Mime           string
	Bytes          int64
	Width          pgtype.Int4
	Height         pgtype.Int4
	DurationMs     pgtype.Int8
	Checksum       pgtype.Text
	Status         string
	PlatformHashes []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        string
	CreatedAt      pgtype.Timestamptz
}

type PerformanceSnapshot struct {
	ID          pgtype.UUID
	CampaignID  pgtype.UUID
	Date        pgtype.Date
	Spend       pgtype.Numeric
	Impressions int64
	Clicks      int64
	Conversions int64
	Reach       int64
	Cpm         pgtype.Numeric
	Cpc         pgtype.Numeric
	Ctr         pgtype.Numeric
	Roas        pgtype.Numeric
	Currency    string
}

type ProviderEvent struct {
	EventID     string
	Type        string
	ProcessedAt pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Wallet struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WalletBalance struct {
	ID           pgtype.UUID
	WalletID     pgtype.UUID
	Currency     string
	BalanceMinor int64
	UpdatedAt    pgtype.Timestamptz
}

type WalletTransaction struct {
	ID                pgtype.UUID
	WalletID          pgtype.UUID
	Currency          string
	Kind              string
	AmountMinor       int64
	BalanceAfterMinor int64
	IdempotencyKey    string
	SourceType        pgtype.Text
	SourceID          pgtype.Text
	FxRate            pgtype.Numeric
	Metadata          []byte
	CreatedAt         pgtype.Timestamptz
}

type Workspace struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	BusinessName       pgtype.Text
	Industry           pgtype.Text
	MonthlyBudget      pgtype.Numeric
	PrimaryGoal        pgtype.Text
	TargetAudience     pgtype.Text
	OnboardingComplete bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	SpendState         string
	SpendStateReason   pgtype.Text
	CommissionRateBps  int32
}
