// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdAccount struct {
	ID                    pgtype.UUID
	WorkspaceID           pgtype.UUID
	Platform              string
	ExternalAccountID     string
	AccessTokenEncrypted  string
	RefreshTokenEncrypted pgtype.Text
	TokenExpiresAt        pgtype.Timestamptz
	Status                string
	ConnectedAt           pgtype.Timestamptz
	PageID                pgtype.Text
	PixelID               pgtype.Text
	Name                  pgtype.Text
}

type CampaignAction struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Actor       string
	Type        string
	Status      string
	Payload     []byte
	Result      []byte
	Error       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Campaign struct {
	ID                   pgtype.UUID
	WorkspaceID          pgtype.UUID
	AdAccountID          pgtype.UUID
	ExternalCampaignID   string
	Name                 string
	Objective            pgtype.Text
	Status               string
	DailyBudget          pgtype.Numeric
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	Cta                  pgtype.Text
	Targeting            []byte
	ExternalAdsetID      pgtype.Text
	ExternalAdID         pgtype.Text
	ExternalCreativeID   pgtype.Text
	Creative             []byte
	BidStrategy          pgtype.Text
	BidCap               pgtype.Numeric
	PacingType           pgtype.Text
	FrequencyCap         pgtype.Int4
	FrequencyCapTimeUnit pgtype.Text
	Variants             []byte
	Provenance           []byte
	Rationale            []byte
}

type Conversation struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Mode        string
	CreatedAt   pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        string
	CreatedAt      pgtype.Timestamptz
}

type PerformanceSnapshot struct {
	ID          pgtype.UUID
	CampaignID  pgtype.UUID
	Date        pgtype.Date
	Spend       pgtype.Numeric
	Impressions int64
	Clicks      int64
	Conversions int64
	Reach       int64
	Cpm         pgtype.Numeric
	Cpc         pgtype.Numeric
	Ctr         pgtype.Numeric
	Roas        pgtype.Numeric
	Currency    string
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	BusinessName       pgtype.Text
	Industry           pgtype.Text
	MonthlyBudget      pgtype.Numeric
	PrimaryGoal        pgtype.Text
	TargetAudience     pgtype.Text
	OnboardingComplete bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
