// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performance_snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAggregatedSummaryByWorkspace = `-- name: GetAggregatedSummaryByWorkspace :one
SELECT
    SUM(ps.spend)::numeric AS total_spend,
    SUM(ps.impressions)::bigint AS total_impressions,
    SUM(ps.clicks)::bigint AS total_clicks,
    SUM(ps.conversions)::bigint AS total_conversions,
    SUM(ps.reach)::bigint AS total_reach,
    AVG(ps.cpm)::numeric AS avg_cpm,
    AVG(ps.cpc)::numeric AS avg_cpc,
    AVG(ps.ctr)::numeric AS avg_ctr,
    AVG(ps.roas)::numeric AS avg_roas
FROM performance_snapshots ps
JOIN campaigns c ON ps.campaign_id = c.id
WHERE c.workspace_id = $1 AND ps.date >= $2 AND ps.date <= $3
`

type GetAggregatedSummaryByWorkspaceParams struct {
	WorkspaceID pgtype.UUID
	Date        pgtype.Date
	Date_2      pgtype.Date
}

type GetAggregatedSummaryByWorkspaceRow struct {
	TotalSpend       pgtype.Numeric
	TotalImpressions int64
	TotalClicks      int64
	TotalConversions int64
	TotalReach       int64
	AvgCpm           pgtype.Numeric
	AvgCpc           pgtype.Numeric
	AvgCtr           pgtype.Numeric
	AvgRoas          pgtype.Numeric
}

func (q *Queries) GetAggregatedSummaryByWorkspace(ctx context.Context, arg GetAggregatedSummaryByWorkspaceParams) (GetAggregatedSummaryByWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getAggregatedSummaryByWorkspace, arg.WorkspaceID, arg.Date, arg.Date_2)
	var i GetAggregatedSummaryByWorkspaceRow
	err := row.Scan(
		&i.TotalSpend,
		&i.TotalImpressions,
		&i.TotalClicks,
		&i.TotalConversions,
		&i.TotalReach,
		&i.AvgCpm,
		&i.AvgCpc,
		&i.AvgCtr,
		&i.AvgRoas,
	)
	return i, err
}

const getSnapshotsByCampaignAndDateRange = `-- name: GetSnapshotsByCampaignAndDateRange :many
SELECT id, campaign_id, date, spend, impressions, clicks, conversions, reach, cpm, cpc, ctr, roas, currency FROM performance_snapshots
WHERE campaign_id = $1 AND date >= $2 AND date <= $3
ORDER BY date
`

type GetSnapshotsByCampaignAndDateRangeParams struct {
	CampaignID pgtype.UUID
	Date       pgtype.Date
	Date_2     pgtype.Date
}

func (q *Queries) GetSnapshotsByCampaignAndDateRange(ctx context.Context, arg GetSnapshotsByCampaignAndDateRangeParams) ([]PerformanceSnapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshotsByCampaignAndDateRange, arg.CampaignID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PerformanceSnapshot
	for rows.Next() {
		var i PerformanceSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Date,
			&i.Spend,
			&i.Impressions,
			&i.Clicks,
			&i.Conversions,
			&i.Reach,
			&i.Cpm,
			&i.Cpc,
			&i.Ctr,
			&i.Roas,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPerformanceSnapshot = `-- name: UpsertPerformanceSnapshot :one
INSERT INTO performance_snapshots (campaign_id, date, spend, impressions, clicks, conversions, reach, cpm, cpc, ctr, roas, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (campaign_id, date)
DO UPDATE SET spend = EXCLUDED.spend, impressions = EXCLUDED.impressions, clicks = EXCLUDED.clicks, conversions = EXCLUDED.conversions, reach = EXCLUDED.reach, cpm = EXCLUDED.cpm, cpc = EXCLUDED.cpc, ctr = EXCLUDED.ctr, roas = EXCLUDED.roas, currency = EXCLUDED.currency
RETURNING id, campaign_id, date, spend, impressions, clicks, conversions, reach, cpm, cpc, ctr, roas, currency
`

type UpsertPerformanceSnapshotParams struct {
	CampaignID  pgtype.UUID
	Date        pgtype.Date
	Spend       pgtype.Numeric
	Impressions int64
	Clicks      int64
	Conversions int64
	Reach       int64
	Cpm         pgtype.Numeric
	Cpc         pgtype.Numeric
	Ctr         pgtype.Numeric
	Roas        pgtype.Numeric
	Currency    string
}

func (q *Queries) UpsertPerformanceSnapshot(ctx context.Context, arg UpsertPerformanceSnapshotParams) (PerformanceSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertPerformanceSnapshot,
		arg.CampaignID,
		arg.Date,
		arg.Spend,
		arg.Impressions,
		arg.Clicks,
		arg.Conversions,
		arg.Reach,
		arg.Cpm,
		arg.Cpc,
		arg.Ctr,
		arg.Roas,
		arg.Currency,
	)
	var i PerformanceSnapshot
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Date,
		&i.Spend,
		&i.Impressions,
		&i.Clicks,
		&i.Conversions,
		&i.Reach,
		&i.Cpm,
		&i.Cpc,
		&i.Ctr,
		&i.Roas,
		&i.Currency,
	)
	return i, err
}

const getDashboardTotals = `-- name: GetDashboardTotals :one
SELECT
    COALESCE(SUM(ps.spend), 0)::numeric AS total_spend,
    COALESCE(SUM(ps.impressions), 0)::bigint AS total_impressions,
    COALESCE(SUM(ps.clicks), 0)::bigint AS total_clicks,
    COALESCE(SUM(ps.conversions), 0)::bigint AS total_conversions,
    COALESCE(AVG(ps.roas), 0)::numeric AS average_roas,
    COALESCE(AVG(ps.cpc), 0)::numeric AS average_cpc
FROM performance_snapshots ps
JOIN campaigns c ON ps.campaign_id = c.id
WHERE c.workspace_id = $1 AND ps.date >= $2 AND ps.date <= $3
`

type GetDashboardTotalsParams struct {
	WorkspaceID pgtype.UUID
	Date        pgtype.Date
	Date_2      pgtype.Date
}

type GetDashboardTotalsRow struct {
	TotalSpend       pgtype.Numeric
	TotalImpressions int64
	TotalClicks      int64
	TotalConversions int64
	AverageRoas      pgtype.Numeric
	AverageCpc       pgtype.Numeric
}

func (q *Queries) GetDashboardTotals(ctx context.Context, arg GetDashboardTotalsParams) (GetDashboardTotalsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardTotals, arg.WorkspaceID, arg.Date, arg.Date_2)
	var i GetDashboardTotalsRow
	err := row.Scan(
		&i.TotalSpend,
		&i.TotalImpressions,
		&i.TotalClicks,
		&i.TotalConversions,
		&i.AverageRoas,
		&i.AverageCpc,
	)
	return i, err
}

const getDashboardDailySeries = `-- name: GetDashboardDailySeries :many
SELECT
    ps.date AS date,
    COALESCE(SUM(ps.spend), 0)::numeric AS spend,
    COALESCE(SUM(ps.conversions), 0)::bigint AS conversions
FROM performance_snapshots ps
JOIN campaigns c ON ps.campaign_id = c.id
WHERE c.workspace_id = $1 AND ps.date >= $2 AND ps.date <= $3
GROUP BY ps.date
ORDER BY ps.date
`

type GetDashboardDailySeriesParams struct {
	WorkspaceID pgtype.UUID
	Date        pgtype.Date
	Date_2      pgtype.Date
}

type GetDashboardDailySeriesRow struct {
	Date        pgtype.Date
	Spend       pgtype.Numeric
	Conversions int64
}

func (q *Queries) GetDashboardDailySeries(ctx context.Context, arg GetDashboardDailySeriesParams) ([]GetDashboardDailySeriesRow, error) {
	rows, err := q.db.Query(ctx, getDashboardDailySeries, arg.WorkspaceID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardDailySeriesRow
	for rows.Next() {
		var i GetDashboardDailySeriesRow
		if err := rows.Scan(&i.Date, &i.Spend, &i.Conversions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardCampaignBreakdown = `-- name: GetDashboardCampaignBreakdown :many
SELECT
    c.id AS campaign_id,
    c.name AS name,
    c.status AS status,
    COALESCE(SUM(ps.spend), 0)::numeric AS spend,
    COALESCE(SUM(ps.impressions), 0)::bigint AS impressions,
    COALESCE(SUM(ps.clicks), 0)::bigint AS clicks,
    COALESCE(SUM(ps.conversions), 0)::bigint AS conversions,
    COALESCE(AVG(ps.roas), 0)::numeric AS average_roas,
    COALESCE(AVG(ps.cpc), 0)::numeric AS average_cpc
FROM campaigns c
LEFT JOIN performance_snapshots ps
    ON ps.campaign_id = c.id AND ps.date >= $2 AND ps.date <= $3
WHERE c.workspace_id = $1
GROUP BY c.id, c.name, c.status
ORDER BY spend DESC
`

type GetDashboardCampaignBreakdownParams struct {
	WorkspaceID pgtype.UUID
	Date        pgtype.Date
	Date_2      pgtype.Date
}

type GetDashboardCampaignBreakdownRow struct {
	CampaignID  pgtype.UUID
	Name        string
	Status      string
	Spend       pgtype.Numeric
	Impressions int64
	Clicks      int64
	Conversions int64
	AverageRoas pgtype.Numeric
	AverageCpc  pgtype.Numeric
}

func (q *Queries) GetDashboardCampaignBreakdown(ctx context.Context, arg GetDashboardCampaignBreakdownParams) ([]GetDashboardCampaignBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getDashboardCampaignBreakdown, arg.WorkspaceID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardCampaignBreakdownRow
	for rows.Next() {
		var i GetDashboardCampaignBreakdownRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.Name,
			&i.Status,
			&i.Spend,
			&i.Impressions,
			&i.Clicks,
			&i.Conversions,
			&i.AverageRoas,
			&i.AverageCpc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
