// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWalletBalance = `-- name: AddWalletBalance :one
UPDATE wallet_balances
SET balance_minor = balance_minor + $3, updated_at = now()
WHERE wallet_id = $1 AND currency = $2
RETURNING id, wallet_id, currency, balance_minor, updated_at
`

type AddWalletBalanceParams struct {
	WalletID     pgtype.UUID
	Currency     string
	BalanceMinor int64
}

func (q *Queries) AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (WalletBalance, error) {
	row := q.db.QueryRow(ctx, addWalletBalance, arg.WalletID, arg.Currency, arg.BalanceMinor)
	var i WalletBalance
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Currency,
		&i.BalanceMinor,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureBillingProfile = `-- name: EnsureBillingProfile :one
INSERT INTO billing_profiles (workspace_id)
VALUES ($1)
ON CONFLICT (workspace_id) DO UPDATE SET updated_at = now()
RETURNING id, workspace_id, provider_customer_id, default_payment_method, billing_mode, created_at, updated_at
`

func (q *Queries) EnsureBillingProfile(ctx context.Context, workspaceID pgtype.UUID) (BillingProfile, error) {
	row := q.db.QueryRow(ctx, ensureBillingProfile, workspaceID)
	var i BillingProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderCustomerID,
		&i.DefaultPaymentMethod,
		&i.BillingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureWallet = `-- name: EnsureWallet :one
INSERT INTO wallets (workspace_id)
VALUES ($1)
ON CONFLICT (workspace_id) DO UPDATE SET updated_at = now()
RETURNING id, workspace_id, status, created_at, updated_at
`

func (q *Queries) EnsureWallet(ctx context.Context, workspaceID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, ensureWallet, workspaceID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureWalletBalance = `-- name: EnsureWalletBalance :one
INSERT INTO wallet_balances (wallet_id, currency)
VALUES ($1, $2)
ON CONFLICT (wallet_id, currency) DO UPDATE SET updated_at = now()
RETURNING id, wallet_id, currency, balance_minor, updated_at
`

type EnsureWalletBalanceParams struct {
	WalletID pgtype.UUID
	Currency string
}

func (q *Queries) EnsureWalletBalance(ctx context.Context, arg EnsureWalletBalanceParams) (WalletBalance, error) {
	row := q.db.QueryRow(ctx, ensureWalletBalance, arg.WalletID, arg.Currency)
	var i WalletBalance
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Currency,
		&i.BalanceMinor,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingProfileByWorkspace = `-- name: GetBillingProfileByWorkspace :one
SELECT id, workspace_id, provider_customer_id, default_payment_method, billing_mode, created_at, updated_at FROM billing_profiles WHERE workspace_id = $1
`

func (q *Queries) GetBillingProfileByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (BillingProfile, error) {
	row := q.db.QueryRow(ctx, getBillingProfileByWorkspace, workspaceID)
	var i BillingProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderCustomerID,
		&i.DefaultPaymentMethod,
		&i.BillingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderEvent = `-- name: GetProviderEvent :one
SELECT event_id, type, processed_at FROM provider_events WHERE event_id = $1
`

func (q *Queries) GetProviderEvent(ctx context.Context, eventID string) (ProviderEvent, error) {
	row := q.db.QueryRow(ctx, getProviderEvent, eventID)
	var i ProviderEvent
	err := row.Scan(&i.EventID, &i.Type, &i.ProcessedAt)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT id, wallet_id, currency, balance_minor, updated_at FROM wallet_balances WHERE wallet_id = $1 AND currency = $2
`

type GetWalletBalanceParams struct {
	WalletID pgtype.UUID
	Currency string
}

func (q *Queries) GetWalletBalance(ctx context.Context, arg GetWalletBalanceParams) (WalletBalance, error) {
	row := q.db.QueryRow(ctx, getWalletBalance, arg.WalletID, arg.Currency)
	var i WalletBalance
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Currency,
		&i.BalanceMinor,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByWorkspace = `-- name: GetWalletByWorkspace :one
SELECT id, workspace_id, status, created_at, updated_at FROM wallets WHERE workspace_id = $1
`

func (q *Queries) GetWalletByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByWorkspace, workspaceID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTransactionByIdempotency = `-- name: GetWalletTransactionByIdempotency :one
SELECT id, wallet_id, currency, kind, amount_minor, balance_after_minor, idempotency_key, source_type, source_id, fx_rate, metadata, created_at FROM wallet_transactions WHERE wallet_id = $1 AND idempotency_key = $2
`

type GetWalletTransactionByIdempotencyParams struct {
	WalletID       pgtype.UUID
	IdempotencyKey string
}

func (q *Queries) GetWalletTransactionByIdempotency(ctx context.Context, arg GetWalletTransactionByIdempotencyParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getWalletTransactionByIdempotency, arg.WalletID, arg.IdempotencyKey)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Currency,
		&i.Kind,
		&i.AmountMinor,
		&i.BalanceAfterMinor,
		&i.IdempotencyKey,
		&i.SourceType,
		&i.SourceID,
		&i.FxRate,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderEvent = `-- name: InsertProviderEvent :one
INSERT INTO provider_events (event_id, type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO UPDATE SET event_id = EXCLUDED.event_id
RETURNING event_id, type, processed_at
`

type InsertProviderEventParams struct {
	EventID string
	Type    string
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (ProviderEvent, error) {
	row := q.db.QueryRow(ctx, insertProviderEvent, arg.EventID, arg.Type)
	var i ProviderEvent
	err := row.Scan(&i.EventID, &i.Type, &i.ProcessedAt)
	return i, err
}

const insertWalletTransaction = `-- name: InsertWalletTransaction :one
INSERT INTO wallet_transactions (wallet_id, currency, kind, amount_minor, balance_after_minor, idempotency_key, source_type, source_id, fx_rate, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (wallet_id, idempotency_key) DO UPDATE SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id, wallet_id, currency, kind, amount_minor, balance_after_minor, idempotency_key, source_type, source_id, fx_rate, metadata, created_at
`

type InsertWalletTransactionParams struct {
	WalletID          pgtype.UUID
	Currency          string
	Kind              string
	AmountMinor       int64
	BalanceAfterMinor int64
	IdempotencyKey    string
	SourceType        pgtype.Text
	SourceID          pgtype.Text
	FxRate            pgtype.Numeric
	Metadata          []byte
}

func (q *Queries) InsertWalletTransaction(ctx context.Context, arg InsertWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, insertWalletTransaction,
		arg.WalletID,
		arg.Currency,
		arg.Kind,
		arg.AmountMinor,
		arg.BalanceAfterMinor,
		arg.IdempotencyKey,
		arg.SourceType,
		arg.SourceID,
		arg.FxRate,
		arg.Metadata,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Currency,
		&i.Kind,
		&i.AmountMinor,
		&i.BalanceAfterMinor,
		&i.IdempotencyKey,
		&i.SourceType,
		&i.SourceID,
		&i.FxRate,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletBalances = `-- name: ListWalletBalances :many
SELECT id, wallet_id, currency, balance_minor, updated_at FROM wallet_balances WHERE wallet_id = $1 ORDER BY currency
`

func (q *Queries) ListWalletBalances(ctx context.Context, walletID pgtype.UUID) ([]WalletBalance, error) {
	rows, err := q.db.Query(ctx, listWalletBalances, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletBalance
	for rows.Next() {
		var i WalletBalance
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Currency,
			&i.BalanceMinor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, wallet_id, currency, kind, amount_minor, balance_after_minor, idempotency_key, source_type, source_id, fx_rate, metadata, created_at FROM wallet_transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Currency,
			&i.Kind,
			&i.AmountMinor,
			&i.BalanceAfterMinor,
			&i.IdempotencyKey,
			&i.SourceType,
			&i.SourceID,
			&i.FxRate,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBillingProfileProvider = `-- name: SetBillingProfileProvider :one
UPDATE billing_profiles
SET provider_customer_id = $2, default_payment_method = $3, billing_mode = $4, updated_at = now()
WHERE workspace_id = $1
RETURNING id, workspace_id, provider_customer_id, default_payment_method, billing_mode, created_at, updated_at
`

type SetBillingProfileProviderParams struct {
	WorkspaceID          pgtype.UUID
	ProviderCustomerID   pgtype.Text
	DefaultPaymentMethod pgtype.Text
	BillingMode          string
}

func (q *Queries) SetBillingProfileProvider(ctx context.Context, arg SetBillingProfileProviderParams) (BillingProfile, error) {
	row := q.db.QueryRow(ctx, setBillingProfileProvider,
		arg.WorkspaceID,
		arg.ProviderCustomerID,
		arg.DefaultPaymentMethod,
		arg.BillingMode,
	)
	var i BillingProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderCustomerID,
		&i.DefaultPaymentMethod,
		&i.BillingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
