// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id)
VALUES ($1)
RETURNING id, user_id, business_name, industry, monthly_budget, primary_goal, target_audience, onboarding_complete, created_at, updated_at
`

func (q *Queries) CreateWorkspace(ctx context.Context, userID pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, userID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Industry,
		&i.MonthlyBudget,
		&i.PrimaryGoal,
		&i.TargetAudience,
		&i.OnboardingComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByUserID = `-- name: GetWorkspaceByUserID :one
SELECT id, user_id, business_name, industry, monthly_budget, primary_goal, target_audience, onboarding_complete, created_at, updated_at FROM workspaces WHERE user_id = $1
`

func (q *Queries) GetWorkspaceByUserID(ctx context.Context, userID pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByUserID, userID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Industry,
		&i.MonthlyBudget,
		&i.PrimaryGoal,
		&i.TargetAudience,
		&i.OnboardingComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOnboardingComplete = `-- name: SetOnboardingComplete :one
UPDATE workspaces
SET onboarding_complete = true, updated_at = now()
WHERE id = $1
RETURNING id, user_id, business_name, industry, monthly_budget, primary_goal, target_audience, onboarding_complete, created_at, updated_at
`

func (q *Queries) SetOnboardingComplete(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, setOnboardingComplete, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Industry,
		&i.MonthlyBudget,
		&i.PrimaryGoal,
		&i.TargetAudience,
		&i.OnboardingComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceProfile = `-- name: UpdateWorkspaceProfile :one
UPDATE workspaces
SET business_name = $2, industry = $3, monthly_budget = $4, primary_goal = $5, target_audience = $6, updated_at = now()
WHERE id = $1
RETURNING id, user_id, business_name, industry, monthly_budget, primary_goal, target_audience, onboarding_complete, created_at, updated_at
`

type UpdateWorkspaceProfileParams struct {
	ID             pgtype.UUID
	BusinessName   pgtype.Text
	Industry       pgtype.Text
	MonthlyBudget  pgtype.Numeric
	PrimaryGoal    pgtype.Text
	TargetAudience pgtype.Text
}

func (q *Queries) UpdateWorkspaceProfile(ctx context.Context, arg UpdateWorkspaceProfileParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceProfile,
		arg.ID,
		arg.BusinessName,
		arg.Industry,
		arg.MonthlyBudget,
		arg.PrimaryGoal,
		arg.TargetAudience,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.Industry,
		&i.MonthlyBudget,
		&i.PrimaryGoal,
		&i.TargetAudience,
		&i.OnboardingComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
